"use client";

import { useMemo } from "react";
import { useFetch } from "./use-fetch";
import {
  computeCostSavings,
  alertsBySite,
  avgResolutionTime,
  completionRate,
} from "@/domain/analytics";
import type { Alert } from "@/types/alert";
import type { WorkOrder } from "@/types/work-order";

interface ApiSiteMinimal {
  id: string;
  name: string;
}

/**
 * Bar chart accent based on alert count relative to max.
 */
function alertCountAccent(
  count: number,
  maxCount: number
): "red" | "amber" | "green" {
  if (count >= maxCount * 0.6) return "red";
  if (count >= maxCount * 0.3) return "amber";
  return "green";
}

/**
 * Format minutes into a human-readable string.
 */
function formatMinutes(minutes: number): string {
  if (minutes < 60) return `${minutes} min`;
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  if (mins === 0) return `${hours}h`;
  return `${hours}h ${mins}m`;
}

/**
 * Generate a relative time string (e.g. "25 min ago", "2 hours ago").
 */
function relativeTime(dateStr: string): string {
  const date = new Date(dateStr);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMin = Math.round(diffMs / (1000 * 60));

  if (diffMin < 1) return "just now";
  if (diffMin < 60) return `${diffMin} min ago`;
  const diffHours = Math.round(diffMin / 60);
  if (diffHours < 24) return `${diffHours} hour${diffHours === 1 ? "" : "s"} ago`;
  const diffDays = Math.round(diffHours / 24);
  return `${diffDays} day${diffDays === 1 ? "" : "s"} ago`;
}

export interface AnalyticsKpi {
  systemUptime: string;
  activeAlerts: string;
  tasksCompleted: string;
  avgResponseTime: string;
}

export interface AlertBySiteBar {
  label: string;
  value: number;
  accent: "red" | "amber" | "green";
}

export interface RecentEvent {
  id: string;
  event: string;
  site: string;
  time: string;
  severity: "critical" | "warning" | "info" | "resolved";
}

export interface AnalyticsData {
  kpis: AnalyticsKpi;
  alertsBySite: AlertBySiteBar[];
  recentEvents: RecentEvent[];
  costSavings: { totalSaved: number; totalRemoteResolutions: number } | null;
  isLoading: boolean;
  error: Error | null;
}

// Fallback KPI values matching the original hardcoded data
const fallbackKpis: AnalyticsKpi = {
  systemUptime: "99.7%",
  activeAlerts: "3",
  tasksCompleted: "42",
  avgResponseTime: "15 min",
};

const fallbackAlertsBySite: AlertBySiteBar[] = [
  { label: "Broken Hill", value: 18, accent: "red" },
  { label: "Svalbard", value: 14, accent: "red" },
  { label: "Pilbara", value: 8, accent: "amber" },
  { label: "Darwin", value: 4, accent: "green" },
  { label: "Kalgoorlie", value: 2, accent: "green" },
  { label: "Atacama", value: 1, accent: "green" },
];

const fallbackRecentEvents: RecentEvent[] = [
  {
    id: "fe1",
    event: "Bearing inspection completed",
    site: "Kalgoorlie Gold Mine",
    time: "25 min ago",
    severity: "resolved",
  },
  {
    id: "fe2",
    event: "Temperature alert triggered",
    site: "Broken Hill Processing",
    time: "1 hour ago",
    severity: "warning",
  },
  {
    id: "fe3",
    event: "Guided session ended",
    site: "Darwin LNG Terminal",
    time: "2 hours ago",
    severity: "info",
  },
  {
    id: "fe4",
    event: "Work order generated by AI",
    site: "Pilbara Iron Ore",
    time: "3 hours ago",
    severity: "info",
  },
  {
    id: "fe5",
    event: "Communication restored",
    site: "Svalbard Data Center",
    time: "5 hours ago",
    severity: "resolved",
  },
];

/**
 * Fetches alerts, work orders, and sites, then computes analytics KPIs
 * using domain logic functions. Falls back to hardcoded data if APIs fail.
 */
export function useAnalytics(): AnalyticsData {
  const {
    data: alertsData,
    isLoading: alertsLoading,
    error: alertsError,
  } = useFetch<Alert[]>("/api/alerts");

  const {
    data: workOrdersData,
    isLoading: workOrdersLoading,
    error: workOrdersError,
  } = useFetch<WorkOrder[]>("/api/work-orders");

  const {
    data: sitesData,
    isLoading: sitesLoading,
    error: sitesError,
  } = useFetch<ApiSiteMinimal[]>("/api/sites");

  const isLoading = alertsLoading || workOrdersLoading || sitesLoading;
  const error = alertsError || workOrdersError || sitesError;

  const hasData = alertsData !== null && workOrdersData !== null;

  const kpis = useMemo((): AnalyticsKpi => {
    if (!hasData) return fallbackKpis;

    const alerts = alertsData!;
    const workOrders = workOrdersData!;

    const activeCount = alerts.filter((a) => a.status === "active").length;
    const completedCount = workOrders.filter(
      (wo) => wo.status === "completed"
    ).length;
    const resolutionTime = avgResolutionTime(alerts);

    // Compute average uptime from sites data or fallback
    const uptimeStr = sitesData && sitesData.length > 0
      ? (() => {
          const sitesFull = sitesData as Array<ApiSiteMinimal & { uptime?: number }>;
          const uptimes = sitesFull
            .map((s) => s.uptime)
            .filter((u): u is number => u !== undefined && u !== null);
          if (uptimes.length === 0) return fallbackKpis.systemUptime;
          const avg = uptimes.reduce((sum, u) => sum + u, 0) / uptimes.length;
          return `${avg.toFixed(1)}%`;
        })()
      : fallbackKpis.systemUptime;

    return {
      systemUptime: uptimeStr,
      activeAlerts: String(activeCount),
      tasksCompleted: String(completedCount),
      avgResponseTime: resolutionTime !== null
        ? formatMinutes(resolutionTime)
        : fallbackKpis.avgResponseTime,
    };
  }, [hasData, alertsData, workOrdersData, sitesData]);

  const alertsBySiteData = useMemo((): AlertBySiteBar[] => {
    if (!alertsData || !sitesData) return fallbackAlertsBySite;

    const siteNames: Record<string, string> = {};
    for (const site of sitesData) {
      siteNames[site.id] = site.name;
    }

    const bySite = alertsBySite(alertsData, siteNames);
    if (bySite.length === 0) return fallbackAlertsBySite;

    const maxCount = bySite[0]?.count ?? 1;

    return bySite.map((entry) => ({
      label: entry.siteName,
      value: entry.count,
      accent: alertCountAccent(entry.count, maxCount),
    }));
  }, [alertsData, sitesData]);

  const recentEvents = useMemo((): RecentEvent[] => {
    if (!alertsData || alertsData.length === 0) return fallbackRecentEvents;

    // Use the most recent alerts as recent events
    return alertsData
      .slice(0, 10)
      .map((alert) => ({
        id: alert.id as string,
        event: alert.title,
        site: (() => {
          if (!sitesData) return alert.siteId as string;
          const site = sitesData.find((s) => s.id === (alert.siteId as string));
          return site?.name ?? (alert.siteId as string);
        })(),
        time: relativeTime(alert.createdAt as string),
        severity: alert.status === "resolved"
          ? ("resolved" as const)
          : alert.severity,
      }));
  }, [alertsData, sitesData]);

  const costSavings = useMemo(() => {
    if (!alertsData) return null;
    const report = computeCostSavings(alertsData, 12000, "This Quarter");
    return {
      totalSaved: report.totalSaved,
      totalRemoteResolutions: report.totalRemoteResolutions,
    };
  }, [alertsData]);

  return {
    kpis,
    alertsBySite: alertsBySiteData,
    recentEvents,
    costSavings,
    isLoading,
    error,
  };
}
